### ISSUE TITLE
怎么部署到服务器啊

### ISSUE THREAD

**Issue by 16eyhuang** [xypecho/vue-full-stack-project#2]

**Comment by xypecho** [comment]
> _No description provided._

不好意思现在才看到，你可以参考我这篇[文章](https://xypecho.github.io/2018/10/03/nodeJs%E9%A1%B9%E7%9B%AE%E9%83%A8%E7%BD%B2%E8%85%BE%E8%AE%AF%E4%BA%91%E5%AE%8C%E6%95%B4%E6%B5%81%E7%A8%8B/)
